### ISSUE TITLE
グループに参加できるようにする

### ISSUE THREAD

**Issue by u-Hoshi** [u-Hoshi/reviewer-decision-app#19]

**Comment by koki-sys** [comment]
- [x] 参照クエリの作成、動作テスト
- [x] GraphQLからtsファイル生成
- [x] 画面作成（レイアウトのみ）
- [x] スタイリング
- [x] ロジック作成
- [x] 動作テスト

**Comment by koki-sys** [comment]
作業完了したため、クローズします。プルリクの連携ができてなかったので手動でクローズします。
